import React from "react";

import {
  GiFurBoot,
  GiCartwheel,
  GiClothes,
  GiCircle,
  GiMegaphone,
  GiCookingPot,
  GiFlamer,
  GiRecycle,
  GiBathtub,
  GiElephant,
  GiCurlyWing,
  GiModernCity,
  GiAnt,
  GiSteak,
  GiShatteredGlass,
  GiLeafSwirl,
  GiPartyPopper,
  GiSpaceship,
  GiPumpkinMask,
  GiPaintBrush,
  GiPill,
  GiWeight,
  GiPartyFlags,
  GiBodySwapping,
  GiPlasticDuck,
  GiGlobe,
  GiWoodPile,
  GiIceSkate,
  GiLion,
  GiBookCover,
  GiPalmTree,
  GiCat,
  GiCherry,
  GiWool,
  GiSharkFin,
} from "react-icons/gi";

import { ImWoman, ImGift, ImMagicWand, ImScissors } from "react-icons/im";

import {
  BsFillStarFill,
  BsHandbagFill,
  BsSnow,
  BsCupStraw,
  BsCameraReelsFill,
  BsThermometerSun,
  BsThermometerSnow,
  BsTools,
  BsSpeedometer,
} from "react-icons/bs";

import {
  IoPlanet,
  IoBuild,
  IoDiamond,
  IoMan,
  IoRocketSharp,
  IoFastFood,
} from "react-icons/io5";

import {
  FaHatWizard,
  FaBaby,
  FaGamepad,
  FaHeartbeat,
  FaCandyCane,
  FaRegLaughBeam,
  FaCampground,
  FaCarrot,
} from "react-icons/fa";

import { MdWork } from "react-icons/md";

// No diacritics allowed
export const animalNames = [
  "Anglerfisch",
  "Albatross",
  "Antilope",
  "Bonobo",
  "Eintagsfliege",
  "Feldhase",
  "Flusspferd",
  "Fledermaus",
  "Flamingo",
  "Honigbiene",
  "Hammerhai",
  "Kaulquappe",
  "Lachsforelle",
  "Laubfrosch",
  "Languste",
  "Nashorn",
  "Opossum",
  "Ozeanschnecke",
  "Papagei",
  "Pelikan",
  "Riesenkrabbe",
  "Rotfuchs",
  "Salamander",
  "Schmetterling",
  "Seehund",
  "Seeschwalbe",
  "Turmfalke",
  "Totenkopfaffe",
  "Wachtel",
  "Weinbergschnecke",
  "Wildschwein",
  "Zwergmaus",
  "Zitronenfalter",
];

export const emojis = [
  "1F0CF.svg",
  "1F408-200D-2B1B.svg",
  "1F48E.svg",
  "1F9AE.svg",
  "1F960.svg",
  "1F9A3.svg",
  "1F380.svg",
  "1F42C.svg",
  "1F419.svg",
  "1F34E.svg",
  "1F35A.svg",
  "1F357.svg",
  "1F431.svg",
  "1F356.svg",
  "1F430.svg",
  "1F43F.svg",
  "1F418.svg",
  "1F42B.svg",
  "1F3B5.svg",
  "1F34D.svg",
  "1F381.svg",
  "E0C0.svg",
  "1F9A2.svg",
  "1F9AD.svg",
  "1F988.svg",
  "1F43D.svg",
  "1F35B.svg",
  "1F368.svg",
  "1F34F.svg",
  "1F3B7.svg",
  "1F432.svg",
  "1F354.svg",
  "1F426.svg",
  "1F427.svg",
  "1F433.svg",
  "1F355.svg",
  "1F369.svg",
  "1F35C.svg",
  "1F382.svg",
  "1F989.svg",
  "1F9A1.svg",
  "1F9C9.svg",
  "1F9A5.svg",
  "1F966.svg",
  "1F9AC.svg",
  "1F999.svg",
  "E0C7.svg",
  "E0CA.svg",
  "1F351.svg",
  "1F437.svg",
  "1F423.svg",
  "1F43A.svg",
  "1F42E.svg",
  "1F379.svg",
  "1F34C.svg",
  "1F42D.svg",
  "1F34B.svg",
  "1F378.svg",
  "1F35F.svg",
  "1F422.svg",
  "1F350.svg",
  "1F436.svg",
  "1F38A.svg",
  "E0C6.svg",
  "1F998.svg",
  "1F9AB.svg",
  "1F967.svg",
  "1F9A4.svg",
  "1F9A6.svg",
  "1F959.svg",
  "1F965.svg",
  "1F420.svg",
  "1F434.svg",
  "1F352.svg",
  "1F42F.svg",
  "1F408.svg",
  "1F43B.svg",
  "1F35D.svg",
  "1F43C.svg",
  "1F409.svg",
  "1F35E.svg",
  "1F34A.svg",
  "1F435.svg",
  "1F353.svg",
  "1F347.svg",
  "1F421.svg",
  "1F38B.svg",
  "1F9AA.svg",
  "1F958.svg",
  "1F9A7.svg",
  "1F415-200D-1F9BA.svg",
  "1F955.svg",
  "1F969.svg",
  "1F996.svg",
  "1F982.svg",
  "E0C8.svg",
  "1F40B.svg",
  "1F438.svg",
  "1F36D.svg",
  "1F41F.svg",
  "1F404.svg",
  "1F362.svg",
  "1F410.svg",
  "1F377.svg",
  "1F411.svg",
  "1F405.svg",
  "1F363.svg",
  "1F37A.svg",
  "1F439.svg",
  "1F40C.svg",
  "1F36E.svg",
  "1F60A.svg",
  "1FAD1.svg",
  "1F983.svg",
  "1F997.svg",
  "1F968.svg",
  "1F954.svg",
  "1F9A9.svg",
  "1F942.svg",
  "1F956.svg",
  "1F9C1.svg",
  "1F981.svg",
  "1F995.svg",
  "1FAD3.svg",
  "crown.svg",
  "1F41E.svg",
  "1F349.svg",
  "1F40A.svg",
  "1F413.svg",
  "1F361.svg",
  "1F407.svg",
  "1F360.svg",
  "1F406.svg",
  "1F412.svg",
  "1F36F.svg",
  "1F41D.svg",
  "1F3A3.svg",
  "1F348.svg",
  "1F60B.svg",
  "1FAD2.svg",
  "1F994.svg",
  "1F980.svg",
  "1F9C0.svg",
  "1F957.svg",
  "1F9A8.svg",
  "1F943.svg",
  "1F9CB.svg",
  "1F953.svg",
  "1F984.svg",
  "1F990.svg",
  "1F60F.svg",
  "1F370.svg",
  "1F416.svg",
  "1F402.svg",
  "1F364.svg",
  "1F37F.svg",
  "1F40D.svg",
  "1F358.svg",
  "1F36B.svg",
  "1F40E.svg",
  "1F36C.svg",
  "1F359.svg",
  "1F41A.svg",
  "1F403.svg",
  "1F365.svg",
  "1F371.svg",
  "1F417.svg",
  "1F61C.svg",
  "1F991.svg",
  "1F985.svg",
  "1F952.svg",
  "1F431-200D-1F4BB.svg",
  "1F9C7.svg",
  "1F950.svg",
  "1F9CA.svg",
  "1F993.svg",
  "1F987.svg",
  "1F60E.svg",
  "1F61A.svg",
  "1F401.svg",
  "1F415.svg",
  "1F3B8.svg",
  "1F36A.svg",
  "1F429.svg",
  "1F41C.svg",
  "1F37E.svg",
  "1F41B.svg",
  "1F428.svg",
  "1F40F.svg",
  "1F414.svg",
  "1F366.svg",
  "1F400.svg",
  "1F986.svg",
  "1F992.svg",
  "1F951.svg",
  "1F43B-200D-2744-FE0F.svg",
  "1FA86.svg",
  "E001.svg",
  "1FA90.svg",
  "1FA85.svg",
  "E1C9.svg",
];

const roundOneRed = [
  "Frau",
  "Berühmtheit",
  "Geschenk",
  "Universum",
  "Arbeit / Uni",
  "Haarig / Pelzig",
];

const roundOneWhite = [
  "Fährt / Rollt",
  "Kleidung / Accessoires",
  "Jung / Neu",
  "Spielzeug / Spiel",
  "Rund",
  "Laut",
];

const roundOneBlue = [
  "Tragbar",
  "Küche",
  "Heiß",
  "Gebaut",
  "Recyclebar",
  "Badezimmer",
];

const roundOneYellow = [
  "Selten",
  "Schwimmt",
  "Groß",
  "Fliegt",
  "Stadt",
  "Klein",
];

const roundOnePurple = [
  "Mit Fleisch / Fleischfresser",
  "Zerbrechlich",
  "Vegetarisch / Pflanzenfresser",
  "Weiß",
  "Süß",
  "Trinkbar",
];

const roundTwoRed = [
  "Mann",
  "Film",
  "Party",
  "Science Fiction",
  "Magisch",
  "Gruselig",
];

const roundTwoWhite = [
  "Kunst",
  "Arzneimittel / Gesundheit",
  "Schwer",
  "Hobby",
  "Lustig",
  "Feiertag",
];

const roundTwoBlue = [
  "Körperteil",
  "Schneidet",
  "Kalt",
  "Werkzeug",
  "Kunststoff",
  "Schnell",
];

const roundTwoYellow = [
  "Land",
  "Raumfahrt",
  "Holz",
  "Rutscht / Gleitet",
  "Zoo",
  "Buch",
];

const roundTwoPurple = [
  "Junk Food",
  "Urlaub",
  "Camping",
  "Schwarz",
  "Orange",
  "Rot",
];

// Icons

export const categoryIcons = {
  Frau: <ImWoman />,
  Berühmtheit: <BsFillStarFill />,
  Geschenk: <ImGift />,
  Universum: <IoPlanet />,
  Zauberer: <FaHatWizard />,
  "Haarig / Pelzig": <GiFurBoot />,
  "Fährt / Rollt": <GiCartwheel />,
  "Kleidung / Accessoires": <GiClothes />,
  "Jung / Neu": <FaBaby />,
  "Spielzeug / Spiel": <FaGamepad />,
  Rund: <GiCircle />,
  Laut: <GiMegaphone />,
  Tragbar: <BsHandbagFill />,
  Küche: <GiCookingPot />,
  Heiß: <GiFlamer />,
  Gebaut: <IoBuild />,
  Recyclebar: <GiRecycle />,
  Badezimmer: <GiBathtub />,
  Selten: <IoDiamond />,
  Gesundheit: <FaHeartbeat />,
  Groß: <GiElephant />,
  Fliegt: <GiCurlyWing />,
  Stadt: <GiModernCity />,
  Klein: <GiAnt />,
  "Mit Fleisch / Fleischfresser": <GiSteak />,
  Zerbrechlich: <GiShatteredGlass />,
  "Vegetarisch / Pflanzenfresser": <GiLeafSwirl />,
  Weiß: <BsSnow />,
  Süß: <FaCandyCane />,
  Trinkbar: <BsCupStraw />,
  Mann: <IoMan />,
  Film: <BsCameraReelsFill />,
  Party: <GiPartyPopper />,
  "Science Fiction": <GiSpaceship />,
  Magisch: <ImMagicWand />,
  Gruselig: <GiPumpkinMask />,
  Kunst: <GiPaintBrush />,
  "Arzneimittel / Gesundheit": <GiPill />,
  Schwer: <GiWeight />,
  "Wird warm": <BsThermometerSun />,
  Lustig: <FaRegLaughBeam />,
  Feiertag: <GiPartyFlags />,
  Körperteil: <GiBodySwapping />,
  Schneidet: <ImScissors />,
  Kalt: <BsThermometerSnow />,
  Werkzeug: <BsTools />,
  Kunststoff: <GiPlasticDuck />,
  Schnell: <BsSpeedometer />,
  Land: <GiGlobe />,
  Raumfahrt: <IoRocketSharp />,
  Holz: <GiWoodPile />,
  "Rutscht / Gleitet": <GiIceSkate />,
  Zoo: <GiLion />,
  Buch: <GiBookCover />,
  "Junk Food": <IoFastFood />,
  Urlaub: <GiPalmTree />,
  Camping: <FaCampground />,
  Schwarz: <GiCat />,
  Orange: <FaCarrot />,
  Rot: <GiCherry />,
  "Arbeit / Uni": <MdWork />,
  Hobby: <GiWool />,
  Schwimmt: <GiSharkFin />,
};

export const roundOneCategories = [
  roundOneRed,
  roundOneBlue,
  roundOneWhite,
  roundOneYellow,
  roundOnePurple,
];

export const roundTwoCategories = [
  roundTwoRed,
  roundTwoBlue,
  roundTwoWhite,
  roundTwoYellow,
  roundTwoPurple,
];

export const combinations = [
  ["red", "slate"],
  ["amber", "purple"],
  ["blue", "red"],
  ["purple", "slate"],
  ["blue", "amber"],
  ["amber", "red"],
  ["blue", "slate"],
  ["red", "purple"],
  ["slate", "amber"],
  ["purple", "blue"],
];

export const colorNumberMap = {
  red: 0,
  blue: 1,
  slate: 2,
  amber: 3,
  purple: 4,
};

export const catColorMap = {
  0: "bg-red-200 text-red-500 shadow-red-200 border-red-500",
  1: "bg-blue-200 text-blue-500 shadow-blue-200 border-blue-500",
  2: "bg-slate-200 text-slate-600 shadow-slate-200 border-slate-500",
  3: "bg-amber-200 text-amber-600 shadow-amber-200 border-amber-500",
  4: "bg-purple-200 text-purple-500 shadow-purple-200 border-purple-500",
};
