import { useState } from "react";
import Head from "next/head";
import Cookies from "universal-cookie";

const Login = () => {
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  async function handleSubmit(e) {
    e.preventDefault();

    const res = await fetch("api/auth", {
      body: JSON.stringify({ password: password }),
      headers: {
        "Content-Type": "application/json",
      },
      method: "POST",
    });

    const json = await res.json();
    if (json.authenticated) {
      const cookies = new Cookies();
      cookies.set("password", password, {
        path: "/",
      });
      window.location.href = "/";
    } else {
      setError("Invalid Password");
    }
  }

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-1/3 max-w-sm mx-auto">
        <form onSubmit={handleSubmit}>
          <label className="block">
            <span className="text-gray-700">Password</span>
            <input
              type="text"
              className="form-input mt-1 block w-full bg-gray-50"
              placeholder="Your site password"
              value={password}
              onChange={(e) => {
                setPassword(e.target.value);
                if (!error) setError("");
              }}
            ></input>
          </label>
          <button
            type="submit"
            className="mt-3 bg-green-400 text-white p-2 font-bold rounded hover:bg-green-600"
          >
            Login
          </button>
          <div>{error}</div>
        </form>
      </div>
    </div>
  );
};

export default Login;
